### ISSUE TITLE
Audacity summary mentions mp3s

### ISSUE THREAD

**Issue by ryanlerch** [hughsie/fedora-appstream#162]
The appdata summary for audacity states that it has support for MP3s, but the version in Fedora is not built with this capability.

I assume we need to keep an override for audacity in the fedora-appstream data that removes mentions of file formats that arent supported in the Fedora builds.

**Comment by hughsie** [comment]
Right. Do you want to handle this, or should I?

**Comment by sergiomb2** [comment]
Audacity-freeworld from RPMFusion had it  ...

**Comment by hughsie** [comment]
I guess this is dead now, MP3 support is freely available in Fedora now.

**Comment by ryanlerch** [comment]
👍

**Comment by sergiomb2** [comment]
Audacity: 
include mp3 import support via libmad, which is now available in Fedora.f25

https://src.fedoraproject.org/cgit/rpms/audacity.git/commit/?id=2a1700bdf815d07dc0ca9c4ceb0160786c395abb
