### ISSUE TITLE
DOSBox appdata

### ISSUE THREAD

**Issue by AsciiWolf** [hughsie/fedora-appstream#169]
https://bugzilla.redhat.com/show_bug.cgi?id=1442849#c2

Upstream seems to be dead, but it would be great if the AppData file could be included downstream in Fedora. It is already used in the Flatpak DOSBox package on Flathub.

**Comment by kalev** [comment]
Thanks, updated the Fedora package.

**Comment by AsciiWolf** [comment]
DOSBox is still missing in GNOME Software on Fedora Rawhide with the latest `appstream-data-29-3.fc29` package installed.

**Comment by kalev** [comment]
Looks like it's not included because of this error during appstream-data compose:
Failed to load icon: icon was too small 32x32: /usr/share/pixmaps/dosbox.png

**Comment by AsciiWolf** [comment]
[Here](https://commons.wikimedia.org/wiki/File:DOSBox_icon.png) is a new icon that is used in the Flatpak DOSBox package. Feel free to use it.

**Comment by kalev** [comment]
Thanks, should be fixed in https://src.fedoraproject.org/rpms/dosbox/c/629635eb39b51e106939ab862bd10b3893dce6b8
