### ISSUE TITLE
Remove "Google Plus" web app

### ISSUE THREAD

**Issue by AsciiWolf** [hughsie/fedora-appstream#171]
Consider removing the "Google Plus" web app from [webapps.xml](https://github.com/hughsie/fedora-appstream/blob/master/appstream-extra/webapps.xml). Google Plus was shut down and the app is no longer useful, but is still shown in GNOME Software on the latest Fedora Rawhide.

**Comment by hughsie** [comment]
Could you do a PR please. Thanks!

**Comment by AsciiWolf** [comment]
@hughsie Done. :-)
